FROM apache/kafka:3.9.1
RUN mkdir -p /opt/kafka/jmx
RUN wget -O /opt/kafka/jmx/jmx_prometheus_exporter.jar https://github.com/prometheus/jmx_exporter/releases/download/1.3.0/jmx_prometheus_javaagent-1.3.0.jar
