{
 "title": "Clickhouse Memory Analysis",
 "description": "ClickHouse Memory Analysis using Prometheus",
 "tags": [
  "clickhouse",
  "db"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ch_node", "label": "Overall Node:", "query": { "query": "ClickHouseAsyncMetrics_Uptime" } }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OS Memory ($ch_node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemory.*\",instance=~\"$ch_node.*\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "ClickHouse Memory ($ch_node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*Memory.*\",__name__ !~ \"ClickHouseAsyncMetrics_.*OSMemory.*\",instance=~\"$ch_node.*\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "jemalloc All  ($ch_node)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "({__name__=~ \"ClickHouseAsyncMetrics_jemalloc.*\", __name__!=\"ClickHouseAsyncMetrics_jemalloc_metadata_thp\", __name__!~ \"ClickHouseAsyncMetrics_jemalloc_background_thread.*\", instance=~\"$ch_node.*\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "OS Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "OS Memory: Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemoryTotal\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OS Memory: Available",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemoryAvailable\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OS Memory: Free Without Cached",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemoryFreeWithoutCached\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OS Memory: Cached",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*Buffers\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OS Memory: Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemoryBuffers\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OS Memory: Swap Cached",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemorySwapCached\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OS Memory: Free Plus Cached",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemoryFreePlusCached\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Clickhouse Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CH Memory: Resident",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*MemoryResident\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CH Memory: Shared",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*MemoryShared\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CH Memory: Code",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*MemoryCode\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CH Memory: Data And Stack",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*MemoryDataAndStack\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CH Memory: Virtual",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*Virtual\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "jemalloc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "jemalloc active",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(job)(ClickHouseAsyncMetrics_jemalloc_active{})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jemalloc allocated",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(job)((ClickHouseAsyncMetrics_jemalloc_allocated))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jemalloc mapped",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(job)((ClickHouseAsyncMetrics_jemalloc_mapped))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jemalloc metadata",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(job)((ClickHouseAsyncMetrics_jemalloc_metadata))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jemalloc resident",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(job)((ClickHouseAsyncMetrics_jemalloc_resident))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jemalloc retained",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(job)((ClickHouseAsyncMetrics_jemalloc_retained))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jemalloc epoch",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(job)((ClickHouseAsyncMetrics_jemalloc_epoch))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jemalloc areas all pdirty",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(job)((ClickHouseAsyncMetrics_jemalloc_arenas_all_pdirty))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jemalloc areas all pmuzzy",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(job)((ClickHouseAsyncMetrics_jemalloc_arenas_all_pmuzzy))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jemalloc areas all pactive",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(job)((ClickHouseAsyncMetrics_jemalloc_arenas_all_pactive))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jemalloc arenas all dirty purged",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(job)((ClickHouseAsyncMetrics_jemalloc_arenas_all_dirty_purged))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jemalloc arenas all muzzy purged",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(job)((ClickHouseAsyncMetrics_jemalloc_arenas_all_muzzy_purged))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}