global:
  scrape_interval: 10s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: ['e-node:9100']
  - job_name: envoy-expoter
    metrics_path: /stats
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['proxy:9901']
  - job_name: mongodb-expoter
    static_configs:
      - targets: ['e-m:9216']
  - job_name: kafka-jmx
    static_configs:
      - targets: ['b-1:7071', 'b-2:7071', 'b-3:7071']
  - job_name: kafka-expoter
    static_configs:
      - targets: ['e-b:9308']
  - job_name: docker-expoter
    static_configs:
      - targets: ['e-docker:8080']
  - job_name: minio-expoter
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['s3-1:9000', 's3-2:9000', 's3-3:9000', 's3-4:9000']
  - job_name: clickhouse-expoter
    static_configs:
      - targets: ['ch-1:9126', 'ch-2:9126', 'ch-3:9126']
  - job_name: clickhouse-keeper-expoter
    static_configs:
      - targets: ['chk-1:9126', 'chk-2:9126', 'chk-3:9126']
  - job_name: panda-exporter
    metrics_path: /public_metrics
    static_configs:
      - targets: ['p-1:9644', 'p-2:9644', 'p-3:9644']
