services:
  s3-init:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: on-failure
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
    command: server http://s3-{1...4}/mnt/drive{1...2}
    entrypoint: >
      /bin/sh -c "
      until mc alias set localminio http://s3-1:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}; do
        echo 'Waiting for MinIO to be ready...';
        sleep 1;
      done;
      mc mb localminio/$${MINIO_BUCKET} || echo 'Bucket already exists';
      mc admin user add localminio $${AWS_ACCESS_KEY} $${AWS_SECRET_KEY} || echo 'User already exists';
      mc admin policy attach localminio readwrite --user $${AWS_ACCESS_KEY} || echo 'Policy already set';
      "
    depends_on: [ s3-1, s3-2, s3-3, s3-4 ]
  s3-1:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: on-failure
    environment:
      MINIO_STORAGE_CLASS_STANDARD: EC:2
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_CACHE_DRIVES: /data
    command: server --console-address 0.0.0.0:35335 http://s3-{1...4}/mnt/drive{1...2}
    ports:
      - 35335:35335
    volumes:
      - s3-1-1:/mnt/drive1
      - s3-1-2:/mnt/drive2
  s3-2:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: on-failure
    environment:
      MINIO_STORAGE_CLASS_STANDARD: EC:2
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_CACHE_DRIVES: /data
    command: server --console-address 0.0.0.0:35335 http://s3-{1...4}/mnt/drive{1...2}
    volumes:
      - s3-2-1:/mnt/drive1
      - s3-2-2:/mnt/drive2
  s3-3:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: on-failure
    environment:
      MINIO_STORAGE_CLASS_STANDARD: EC:2
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_CACHE_DRIVES: /data
    command: server --console-address 0.0.0.0:35335 http://s3-{1...4}/mnt/drive{1...2}
    volumes:
      - s3-3-1:/mnt/drive1
      - s3-3-2:/mnt/drive2
  s3-4:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: on-failure
    environment:
      MINIO_STORAGE_CLASS_STANDARD: EC:2
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_CACHE_DRIVES: /data
    command: server --console-address 0.0.0.0:35335 http://s3-{1...4}/mnt/drive{1...2}
    volumes:
      - s3-4-1:/mnt/drive1
      - s3-4-2:/mnt/drive2
